In [44]:
import pandas as pd
df = pd.read_csv(r"E:\Data Analyst Portfolio\Loan Approval\Loan_approval.csv")

In [45]:
df.head()

,Application_ID,Age,Gender,Marital_Status,Education_Level,Employment_Status,Job_Experience_Years,Annual_Income,Monthly_Income,Credit_Score,...,Co_Applicant,Collateral,Application_Channel,Region,Bank_Account_Age_Years,Previous_Loan_Status,Risk_Score,Default_Risk,Approved_Amount,Loan_Approved
0,500001,26,Female,Single,Bachelor,Contract,5,64389.73,5365.81,584,...,No,No,Branch,South,1.8,Paid Off,68.80,High,34868.81,Approved
1,500002,49,Female,Divorced,Bachelor,Salaried,11,81487.69,6790.64,596,...,Yes,No,Branch,North,10.3,Paid Off,60.24,Medium,77250.62,Approved
2,500003,20,Male,Married,Master,Business Owner,1,96833.02,8069.42,850,...,No,Yes,Agent,North,1.5,Paid Off,30.61,Low,69245.99,Approved
3,500004,50,Male,Married,High School,Salaried,20,108291.76,9024.31,626,...,No,No,Online,North,21.0,Paid Off,25.73,Low,36760.89,Approved
4,500005,63,Male,Married,Bachelor,Self-Employed,28,142262.74,11855.23,559,...,Yes,Yes,Online,West,24.6,Paid Off,39.82,Medium,62344.90,Approved

In [46]:
df.shape

(30000, 36)

In [42]:
df.columns.tolist()

['Application_ID',
 'Age',
 'Gender',
 'Marital_Status',
 'Education_Level',
 'Employment_Status',
 'Job_Experience_Years',
 'Annual_Income',
 'Monthly_Income',
 'Credit_Score',
 'Credit_History_Years',
 'Existing_Loans',
 'Late_Payments_Last_2_Years',
 'Loan_Amount',
 'Loan_Term_Months',
 'Loan_Purpose',
 'Interest_Rate',
 'Debt_To_Income_Ratio',
 'Savings_Balance',
 'Checking_Balance',
 'Total_Assets',
 'Total_Liabilities',
 'Monthly_Debt_Payment',
 'Property_Ownership',
 'Residential_Status',
 'Dependents',
 'Co_Applicant',
 'Collateral',
 'Application_Channel',
 'Region',
 'Bank_Account_Age_Years',
 'Previous_Loan_Status',
 'Risk_Score',
 'Default_Risk',
 'Approved_Amount',
 'Loan_Approved',
 'Loan_to_Income_Ratio',
 'Net_Worth',
 'Liquid_Assets',
 'Approval_Gap',
 'Credit_Score_Band',
 'Income_Band',
 'DTI_Band',
 'Risk_Flag']

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Application_ID              30000 non-null  int64
 1   Age                         30000 non-null  int64
 2   Gender                      30000 non-null  str
 3   Marital_Status              30000 non-null  str
 4   Education_Level             30000 non-null  str
 5   Employment_Status           30000 non-null  str
 6   Job_Experience_Years        30000 non-null  int64
 7   Annual_Income               30000 non-null  float64
 8   Monthly_Income              30000 non-null  float64
 9   Credit_Score                30000 non-null  int64
 10  Credit_History_Years        30000 non-null  float64
 11  Existing_Loans              30000 non-null  int64
 12  Late_Payments_Last_2_Years  30000 non-null  int64
 13  Loan_Amount                 30000 non-null  float64
 14  Loan_Term_Months            30000 non-null  int64
 15  Loan_Purpose                30000 non-null  str
 16  Interest_Rate               30000 non-null  float64
 17  Debt_To_Income_Ratio        30000 non-null  float64
 18  Savings_Balance             30000 non-null  float64
 19  Checking_Balance            30000 non-null  float64
 20  Total_Assets                30000 non-null  float64
 21  Total_Liabilities           30000 non-null  float64
 22  Monthly_Debt_Payment        30000 non-null  float64
 23  Property_Ownership          30000 non-null  str
 24  Residential_Status          30000 non-null  str
 25  Dependents                  30000 non-null  int64
 26  Co_Applicant                30000 non-null  str
 27  Collateral                  30000 non-null  str
 28  Application_Channel         30000 non-null  str
 29  Region                      30000 non-null  str
 30  Bank_Account_Age_Years      30000 non-null  float64
 31  Previous_Loan_Status        30000 non-null  str
 32  Risk_Score                  30000 non-null  float64
 33  Default_Risk                30000 non-null  str
 34  Approved_Amount             30000 non-null  float64
 35  Loan_Approved               30000 non-null  str
 36  Loan_to_Income_Ratio        30000 non-null  float64
 37  Net_Worth                   30000 non-null  float64
 38  Liquid_Assets               30000 non-null  float64
 39  Approval_Gap                30000 non-null  float64
 40  Credit_Score_Band           30000 non-null  category
 41  Income_Band                 30000 non-null  category
 42  DTI_Band                    30000 non-null  category
 43  Risk_Flag                   30000 non-null  bool
dtypes: bool(1), category(3), float64(18), int64(8), str(14)
memory usage: 9.3 MB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

,Application_ID,Age,Job_Experience_Years,Annual_Income,Monthly_Income,Credit_Score,Credit_History_Years,Existing_Loans,Late_Payments_Last_2_Years,Loan_Amount,...,Debt_To_Income_Ratio,Savings_Balance,Checking_Balance,Total_Assets,Total_Liabilities,Monthly_Debt_Payment,Dependents,Bank_Account_Age_Years,Risk_Score,Approved_Amount
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,515000.500000,39.039167,11.045567,88782.272872,7398.522735,679.076133,8.926737,1.285367,0.765400,134837.206170,...,10.618963,31624.308586,9709.789039,3.157926e+05,67042.822829,749.972164,1.200933,10.466123,48.445368,53839.711882
std,8660.398374,10.619761,7.115151,30350.252156,2529.187664,88.463305,6.789311,1.202877,1.104387,84259.952016,...,9.691352,21795.230635,6518.205071,1.885391e+05,48864.242649,708.284092,1.091573,7.175011,23.728828,62248.940327
min,500001.000000,18.000000,0.000000,5000.000000,416.670000,300.000000,0.000000,0.000000,0.000000,1000.000000,...,0.010000,0.000000,0.000000,3.619240e+03,62.830000,0.450000,0.000000,0.000000,0.000000,0.000000
25%,507500.750000,32.000000,6.000000,68085.915000,5673.825000,619.000000,3.600000,0.000000,0.000000,67549.647500,...,4.180000,14741.392500,4459.967500,1.635529e+05,30549.262500,281.620000,0.000000,5.000000,31.060000,0.000000
50%,515000.500000,39.000000,10.000000,88623.070000,7385.255000,681.000000,7.500000,1.000000,0.000000,121347.455000,...,7.880000,28059.240000,8726.320000,2.859038e+05,54877.025000,537.400000,1.000000,9.200000,46.210000,37526.300000
75%,522500.250000,46.000000,15.000000,109101.035000,9091.750000,741.000000,12.900000,2.000000,1.000000,189424.865000,...,13.792500,44643.770000,13951.940000,4.351533e+05,91658.432500,974.062500,2.000000,14.700000,63.700000,91926.145000
max,530000.000000,70.000000,44.000000,211985.400000,17665.450000,850.000000,41.200000,8.000000,10.000000,500000.000000,...,95.000000,154420.280000,43832.880000,1.292422e+06,399610.260000,7964.720000,6.000000,40.000000,100.000000,393109.690000

In [12]:
# Data validation
# 1. Check categorical values
for col in ['Gender', 'Marital_Status', 'Education_Level',
            'Employment_Status', 'Loan_Purpose',
            'Property_Ownership', 'Residential_Status',
            'Co_Applicant', 'Collateral',
            'Application_Channel', 'Region',
            'Previous_Loan_Status', 'Default_Risk',
            'Loan_Approved']:
    
    print("\n", col)
    print(df[col].value_counts())

 Gender
Gender
Male      16771
Female    13229
Name: count, dtype: int64

 Marital_Status
Marital_Status
Married     15511
Single      10269
Divorced     3023
Widowed      1197
Name: count, dtype: int64

 Education_Level
Education_Level
Bachelor       13939
High School     8403
Master          6460
PhD             1198
Name: count, dtype: int64

 Employment_Status
Employment_Status
Salaried          15063
Self-Employed      5423
Business Owner     3604
Contract           3536
Unemployed         2374
Name: count, dtype: int64

 Loan_Purpose
Loan_Purpose
Car                   4349
Debt Consolidation    4331
Medical               4330
Personal              4310
Home                  4245
Education             4242
Business              4193
Name: count, dtype: int64

 Property_Ownership
Property_Ownership
Rent            10802
Own              8465
Mortgage         6536
Family Owned     4197
Name: count, dtype: int64

 Residential_Status
Residential_Status
Urban       14407
Suburban    10196
Rural        5397
Name: count, dtype: int64

 Co_Applicant
Co_Applicant
No     21154
Yes     8846
Name: count, dtype: int64

 Collateral
Collateral
No     18480
Yes    11520
Name: count, dtype: int64

 Application_Channel
Application_Channel
Online        12629
Branch         7763
Mobile App     6662
Agent          2946
Name: count, dtype: int64

 Region
Region
South      6088
Central    6064
East       6017
North      5951
West       5880
Name: count, dtype: int64

 Previous_Loan_Status
Previous_Loan_Status
Paid Off            12614
No Previous Loan     8925
Active               6650
Defaulted            1811
Name: count, dtype: int64

 Default_Risk
Default_Risk
Medium    13593
Low        9374
High       7033
Name: count, dtype: int64

 Loan_Approved
Loan_Approved
Approved    17291
Rejected    12709
Name: count, dtype: int64

In [13]:
# 2. Check important numeric ranges
df[['Age',
    'Credit_Score',
    'Job_Experience_Years',
    'Existing_Loans',
    'Late_Payments_Last_2_Years',
    'Loan_Term_Months',
    'Debt_To_Income_Ratio',
    'Dependents',
    'Risk_Score',
    'Interest_Rate']].describe()

,Age,Credit_Score,Job_Experience_Years,Existing_Loans,Late_Payments_Last_2_Years,Loan_Term_Months,Debt_To_Income_Ratio,Dependents,Risk_Score,Interest_Rate
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,39.039167,679.076133,11.045567,1.285367,0.765400,112.187600,10.618963,1.200933,48.445368,13.960015
std,10.619761,88.463305,7.115151,1.202877,1.104387,102.108838,9.691352,1.091573,23.728828,2.123708
min,18.000000,300.000000,0.000000,0.000000,0.000000,12.000000,0.010000,0.000000,0.000000,5.610000
25%,32.000000,619.000000,6.000000,0.000000,0.000000,36.000000,4.180000,0.000000,31.060000,12.530000
50%,39.000000,681.000000,10.000000,1.000000,0.000000,72.000000,7.880000,1.000000,46.210000,13.770000
75%,46.000000,741.000000,15.000000,2.000000,1.000000,180.000000,13.792500,2.000000,63.700000,15.130000
max,70.000000,850.000000,44.000000,8.000000,10.000000,360.000000,95.000000,6.000000,100.000000,24.820000

In [15]:
#3. Check whether income is logically consistent
(df['Annual_Income'] / 12 - df['Monthly_Income']).describe()

count    30000.000000
mean         0.000005
std          0.002889
min         -0.005000
25%         -0.002500
50%          0.000000
75%          0.002500
max          0.005000
dtype: float64

In [16]:
# 4. Check loan approval consistency
df.groupby('Loan_Approved')[['Loan_Amount', 'Approved_Amount']].agg(
    ['count', 'mean', 'min', 'max']
)

              Loan_Amount                                  Approved_Amount  \
                    count           mean     min       max           count
Loan_Approved
Approved            17291  126513.957337  1000.0  500000.0           17291
Rejected            12709  146161.251774  1000.0  500000.0           12709


                       mean     min        max
Loan_Approved
Approved       93412.258196  1000.0  393109.69
Rejected           0.000000     0.0       0.00

In [19]:
# 5. Find suspicious approval records
df[df['Loan_Approved'] == 'No']['Approved_Amount'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Approved_Amount, dtype: float64

In [20]:
# Feature Engineering --> more useful for credit-risk analysis.
# 1. Loan-to-Income Ratio
df['Loan_to_Income_Ratio'] = (
    df['Loan_Amount'] / df['Annual_Income']
)

In [21]:
# 2. Net Worth
df['Net_Worth'] = (
    df['Total_Assets'] - df['Total_Liabilities']
)

In [22]:
# 3. Liquid Assets
df['Liquid_Assets'] = (
    df['Savings_Balance'] + df['Checking_Balance']
)

In [23]:
# 4. Approval Gap
df['Approval_Gap'] = (
    df['Loan_Amount'] - df['Approved_Amount']
)

In [24]:
# -> Credit Score Band
df['Credit_Score_Band'] = pd.cut(
    df['Credit_Score'],
    bins=[0, 579, 669, 739, 799, 850],
    labels=['Poor', 'Fair', 'Good', 'Very Good', 'Excellent']
)

In [25]:
df[['Loan_to_Income_Ratio',
    'Net_Worth',
    'Liquid_Assets',
    'Approval_Gap',
    'Credit_Score_Band']].head()

,Loan_to_Income_Ratio,Net_Worth,Liquid_Assets,Approval_Gap,Credit_Score_Band
0,2.297474,101572.33,17483.53,113064.93,Fair
1,2.208626,211799.41,25762.14,102725.18,Fair
2,2.278603,438475.95,57101.08,151398.04,Excellent
3,0.339462,542871.65,40764.03,0.00,Fair
4,0.438238,700648.57,97454.43,0.00,Poor

In [26]:
df['Credit_Score_Band'].value_counts().sort_index()

Credit_Score_Band
Poor         4048
Fair         9448
Good         8795
Very Good    4937
Excellent    2772
Name: count, dtype: int64

In [28]:
# Your First Real Business Analysis
approval_rate = (
    df.groupby('Credit_Score_Band')['Loan_Approved']
      .value_counts(normalize=True)
      .unstack()
      .fillna(0)
      .mul(100)
      .round(2)
)

approval_rate

Loan_Approved      Approved  Rejected
Credit_Score_Band
Poor                  10.94     89.06
Fair                  47.56     52.44
Good                  66.97     33.03
Very Good             80.68     19.32
Excellent             89.54     10.46

In [29]:
df['Income_Band'] = pd.qcut(
    df['Annual_Income'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

In [30]:
income_approval = (
    df.groupby('Income_Band', observed=True)['Loan_Approved']
      .value_counts(normalize=True)
      .unstack()
      .fillna(0)
      .mul(100)
      .round(2)
)

income_approval

Loan_Approved  Approved  Rejected
Income_Band
Very Low          41.47     58.53
Low               51.23     48.77
Medium            62.38     37.62
High              65.82     34.18
Very High         67.28     32.72

In [31]:
# Default Risk vs Credit Score
risk_by_credit = (
    df.groupby('Credit_Score_Band')['Default_Risk']
      .value_counts(normalize=True)
      .unstack()
      .fillna(0)
      .mul(100)
      .round(2)
)

risk_by_credit

Default_Risk        High    Low  Medium
Credit_Score_Band
Poor               79.03   0.64   20.33
Fair               26.81  14.08   59.11
Good               11.42  34.93   53.66
Very Good           4.90  58.90   36.20
Excellent           1.98  73.52   24.49

In [32]:
 # DTI vs Default Risk
df['DTI_Band'] = pd.cut(
    df['Debt_To_Income_Ratio'],
    bins=[0, 10, 20, 30, 100],
    labels=['Low', 'Moderate', 'High', 'Very High']
)

In [33]:
dti_risk = (
    df.groupby('DTI_Band', observed=True)['Default_Risk']
      .value_counts(normalize=True)
      .unstack()
      .fillna(0)
      .mul(100)
      .round(2)
)

dti_risk

Default_Risk   High    Low  Medium
DTI_Band
Low           15.00  41.48   43.52
Moderate      30.35  18.71   50.94
High          41.93  10.70   47.37
Very High     63.10   3.04   33.86

In [34]:
# Late Payments → Default Risk
late_payment_risk = (
    df.groupby('Late_Payments_Last_2_Years')['Default_Risk']
      .value_counts(normalize=True)
      .unstack()
      .fillna(0)
      .mul(100)
      .round(2)
)

late_payment_risk

Default_Risk                  High    Low  Medium
Late_Payments_Last_2_Years
0                            12.92  40.06   47.02
1                            21.43  28.18   50.38
2                            43.18  14.00   42.82
3                            71.50   4.10   24.40
4                            89.93   0.67    9.40
5                            96.95   0.00    3.05
6                            97.27   0.00    2.73
7                            97.14   0.00    2.86
8                           100.00   0.00    0.00
9                           100.00   0.00    0.00
10                          100.00   0.00    0.00

In [35]:
# Advanced Risk Segmentation
df['Risk_Flag'] = (
    (df['Credit_Score'] < 580) |
    (df['Debt_To_Income_Ratio'] > 30) |
    (df['Late_Payments_Last_2_Years'] >= 3)
)

In [36]:
risk_approval = (
    df.groupby('Risk_Flag')['Loan_Approved']
      .value_counts(normalize=True)
      .unstack()
      .fillna(0)
      .mul(100)
      .round(2)
)

risk_approval

Loan_Approved  Approved  Rejected
Risk_Flag
False             66.98     33.02
True              16.23     83.77

In [37]:
df.to_csv(
    r"E:\Data Analyst Portfolio\Loan Approval\Loan_approval_cleaned.csv",
    index=False
)

In [38]:
import os

os.path.exists(
    r"E:\Data Analyst Portfolio\Loan Approval\Loan_approval_cleaned.csv"
)

True

In [39]:
df.to_csv(
    r"E:\Data Analyst Portfolio\Loan Approval\Loan_approval_final.csv",
    index=False
)